version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - SECRET_KEY=your-secret-key-change-in-production
    command: uvicorn jobhuntgpt.api:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - jobhuntgpt-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - jobhuntgpt-network

networks:
  jobhuntgpt-network:
    driver: bridge
